### PR TITLE
➕ Added Replace text feature #15

### PR DESCRIPTION
**Pull request by SGI-CAPP-AT2**
- added inputs for word and replace with word
- added gitignore to ignore node_modules automatically while commit
_After Results_
image

ShGI

### CODE REVIEW

**Comment by GauriKashyap** [comment]
@SGI-CAPP-AT2 Good job!....Can you organize the buttons in a better way?

**Comment by SGI-CAPP-AT2** [comment]
> @SGI-CAPP-AT2 Good job!....Can you organize the buttons in a better way?

yes

**Comment by SGI-CAPP-AT2** [comment]
image
@GauriKashyap Check this

**Comment by SGI-CAPP-AT2** [comment]
image
@GauriKashyap Check this

**Comment by GauriKashyap** [comment]
How about, having showing the replace word instance, only if the user wants to replace something? Can you give a button in navbar, through which these becomes visible? 
Also, provide some line spacing between the word replace box and the upper default buttons.
Make these changes and send a PR, make sure you don't have any merge conflicts

**Comment by SGI-CAPP-AT2** [comment]
> How about, having showing the replace word instance, only if the user wants to replace something? Can you give a button in navbar, through which these becomes visible? 
> Also, provide some line spacing between the word replace box and the upper default buttons.
> Make these changes and send a PR, make sure you don't have any merge conflicts
> 

Okay lemme do it

**Comment by SGI-CAPP-AT2** [comment]
@GauriKashyap 
[screen-capture (2).webm](https://user-images.githubusercontent.com/77089227/193398350-962c0057-e0f3-47f1-9b5b-da298fe810d7.webm)
Check this out

**Comment by SGI-CAPP-AT2** [comment]
@GauriKashyap Check it out 
and let me know if any issue

**Comment by GauriKashyap** [comment]
I still feel the indentation of buttons, don't look good, can you make it look better somehow.

Screenshot 2022-10-01 at 4 22 35 PM

**Comment by SGI-CAPP-AT2** [comment]
> I still feel the indentation of buttons, don't look good, can you make it look better somehow.
> 
> Screenshot 2022-10-01 at 4 22 35 PM
> 

You mean margin in between

**Comment by SGI-CAPP-AT2** [comment]
image

**Comment by SGI-CAPP-AT2** [comment]
@GauriKashyap Can you look at this again ?

**Comment by GauriKashyap** [comment]
> @GauriKashyap Can you look at this again ?

Yeah make the suitable changes and commit.

**Comment by SGI-CAPP-AT2** [comment]
> > @GauriKashyap Can you look at this again ?
> 
> Yeah make the suitable changes and commit.

https://text-utilis-2wbk3g34i-gaurikashyap.vercel.app/
Already done !

**Comment by SGI-CAPP-AT2** [comment]
@GauriKashyap Can You look at this again ?

**Comment by GauriKashyap** [comment]
See the updated website and make the changes accordingly, just make the changes in the updated versions of the website and submit

**Comment by SGI-CAPP-AT2** [comment]
@GauriKashyap Let the PR get Merged NOW !
Before any conflicts

**Comment by SGI-CAPP-AT2** [comment]
@GauriKashyap

**Comment by SGI-CAPP-AT2** [comment]
@GauriKashyap you haven't merged ?

**Pull request closed without merging**
