### PR TITLE
Enhancement/improve UI

### PR DESCRIPTION
**Pull request by andreaevolo**
I imporoved the UI and changed the buttons ordering.

### CODE REVIEW

**Comment by PanwarAyush** [comment]
@andreaevolo  Please try to remove conflicts!

**Comment by andreaevolo** [comment]
@PanwarAyush Done! 😃

**Comment by PanwarAyush** [comment]
> @PanwarAyush Done! 😃

amazing work!

**Comment by GauriKashyap** [comment]
Good work @andreaevolo

**Pull request merged**
